from __future__ import annotations

from typing import Awaitable, Callable, Mapping, Protocol

from code_agent.core._json import JSONValue
from code_agent.core.limits import TaskBudget
from code_agent.core.task import TaskRecord, TaskStatus
from code_agent.core.task_state import TaskState
from code_agent.sessions.models import CheckpointRecord, GoalRecord, MessageRecord
from code_agent.sessions.workspace_models import (
    CheckpointCursor,
    RewindOperationRecord,
    WorkspaceLineageRecord,
    WorkspaceSnapshotRecord,
)
from code_agent.workspace._snapshot_manifest import MaterializedSnapshot, SnapshotManifest
from code_agent.workspace.edits import WorkspaceSnapshot
from code_agent.workspace.inventory import WorkspaceInventory


class AsyncLease(Protocol):
    async def __aenter__(self) -> object: ...
    async def __aexit__(self, *args: object) -> object: ...


class LineageLocks(Protocol):
    def for_lineage(self, lineage_id: str) -> AsyncLease: ...


class CheckpointWorkspacePort(Protocol):
    async def inventory(self) -> WorkspaceInventory: ...
    async def snapshot(self, paths: tuple[str, ...]) -> WorkspaceSnapshot: ...
    async def store(
        self, snapshot: WorkspaceSnapshot, modes: Mapping[str, int]
    ) -> SnapshotManifest: ...
    async def materialize(
        self, snapshot: WorkspaceSnapshotRecord
    ) -> MaterializedSnapshot: ...
    async def restore(
        self,
        checkpoint_id: str,
        snapshot: MaterializedSnapshot,
        current_paths: tuple[str, ...],
    ) -> None: ...


class CheckpointSessionsPort(Protocol):
    async def load_task(self, task_id: str) -> TaskRecord: ...
    async def load_lineage_for_task(self, task_id: str) -> WorkspaceLineageRecord: ...
    async def load_lineage(self, lineage_id: str) -> WorkspaceLineageRecord: ...
    async def load_message_records(self, thread_id: str) -> tuple[MessageRecord, ...]: ...
    async def latest_event_sequence(self, thread_id: str) -> int: ...
    async def list_goals(self, thread_id: str) -> tuple[GoalRecord, ...]: ...
    async def load_task_state(self, thread_id: str) -> TaskState: ...
    async def load_task_budget(self, task_id: str) -> TaskBudget: ...
    async def publish_workspace_checkpoint(
        self, thread_id: str, label: str, metadata: Mapping[str, JSONValue],
        snapshot: WorkspaceSnapshotRecord | None, cursor: CheckpointCursor,
    ) -> str: ...
    async def list_checkpoints(self, thread_id: str) -> tuple[CheckpointRecord, ...]: ...
    async def load_checkpoint_cursor(self, checkpoint_id: str) -> CheckpointCursor: ...
    async def load_workspace_snapshot(
        self, checkpoint_id: str
    ) -> WorkspaceSnapshotRecord | None: ...
    async def begin_rewind(self, operation: object, rollback_checkpoint_id: str): ...
    async def fork_task_from_checkpoint(self, checkpoint_id: str) -> TaskRecord: ...
    async def transfer_lineage_owner(
        self, lineage_id: str, expected_owner_task_id: str, new_owner_task_id: str
    ) -> WorkspaceLineageRecord: ...
    async def transition_task(
        self, task_id: str, status: TaskStatus, reason: str | None = None
    ) -> TaskRecord: ...
    async def complete_rewind(
        self, operation_id: str, replacement_task_id: str | None = None
    ) -> RewindOperationRecord: ...
    async def fail_rewind(
        self, operation_id: str, error_code: str, *, recovery_required: bool = False
    ) -> RewindOperationRecord: ...
    async def pending_rewinds(
        self, lineage_id: str | None = None
    ) -> tuple[RewindOperationRecord, ...]: ...


Quiesce = Callable[[str], Awaitable[None]]
InvalidateCache = Callable[[tuple[str, ...]], object]
InvalidateVerification = Callable[[str, str | None], object]
BlockLineage = Callable[[str, tuple[str, ...], str], object]
